language: node_js
node_js:
  - "5.11"

services:
  - docker
  - postgresql

# command to install dependencies
install:
  - cd api && npm install
  - cp app/config/db-config.js.travis app/config/db-config.js
  - cp app/config/api-config.js.deploy app/config/api-config.js

# commands to run before tests
before_script:
  - npm install -g codeclimate-test-reporter
  - psql -c 'create database travis' -U postgres
  - ./node_modules/.bin/db-migrate up

# command to run tests
script: npm run test-coverage

# build and push docker image
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
  - ./bot.sh build
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./bot.sh push "$TRAVIS_BRANCH"
  - cd ..

deploy:
  provider: elasticbeanstalk
  app: flash-api
  env: develop-flash-app-stsilabs
  bucket_name: eb.flash-api
  bucket_path: develop
  zip_file: Dockerrun.aws.json
  on:
    branch: develop
