ALTER TABLE users ALTER COLUMN title DROP NOT NULL;
ALTER TABLE users ALTER COLUMN organization DROP NOT NULL;
ALTER TABLE users ALTER COLUMN department DROP NOT NULL;
ALTER TABLE users ALTER COLUMN role DROP NOT NULL;
