ALTER TABLE users ALTER COLUMN title SET NOT NULL;
ALTER TABLE users ALTER COLUMN organization SET NOT NULL;
ALTER TABLE users ALTER COLUMN department SET NOT NULL;
ALTER TABLE users ALTER COLUMN role SET NOT NULL;
