INSERT INTO users VALUES ('gwashington', 'George Washington', 'CEO', 'STSI', 'Department A');
INSERT INTO users VALUES ('jadams', 'John Adams', 'CTO', 'STSI', 'Department B');
INSERT INTO users VALUES ('tjefferson', 'Thomas Jefferson', 'CFO', 'STSI', 'Department C');
INSERT INTO users VALUES ('jmadison', 'James Madison', 'COO', 'STSI', 'Department A');
INSERT INTO users VALUES ('jmonroe', 'James Monroe', 'Project Manager', 'STSI', 'Department B');
INSERT INTO users VALUES ('jqadams', 'John Quincy Adams', 'Project Manager', 'STSI', 'Department C');
INSERT INTO users VALUES ('ajackson', 'Andrew Jackson', 'Business Analyst', 'STSI', 'Department A');
INSERT INTO users VALUES ('mvanburen', 'Martin Van Buren', 'Business Analyst', 'STSI', 'Department B');
INSERT INTO users VALUES ('wharrison', 'William Harrison', 'Business Analyst', 'STSI', 'Department C');
INSERT INTO users VALUES ('jtyler', 'John Tyler', 'Business Analyst', 'STSI', 'Department A');
INSERT INTO users VALUES ('jpolk', 'James Polk', 'Business Analyst', '540.co', 'Department B');
INSERT INTO users VALUES ('ztaylor', 'Zachery Taylor', 'Solutions Architect', '540.co', 'Department C');
INSERT INTO users VALUES ('mfilmore', 'Millard Fillmore', 'Solutions Architect', '540.co', 'Department A');
INSERT INTO users VALUES ('fpierce', 'Franklin Pierce', 'Solutions Architect', '540.co', 'Department B');
INSERT INTO users VALUES ('jbuchanan', 'James Buchanan', 'ScrumMaster', '540.co', 'Department C');
INSERT INTO users VALUES ('alincoln', 'Abraham Lincoln', 'ScrumMaster', '540.co', 'Department A');
INSERT INTO users VALUES ('ajohnson', 'Andrew Johnson', 'UI/UX Expert', '540.co', 'Department B');
INSERT INTO users VALUES ('ugrant', 'Ulysses S. Grant', 'UI/UX Expert', '540.co', 'Department C');
INSERT INTO users VALUES ('rhayes', 'Rutherford B. Hayes', 'UI/UX Expert', '540.co', 'Department A');
INSERT INTO users VALUES ('jgarfield', 'James Garfield', 'UI/UX Expert', '540.co', 'Department B');
INSERT INTO users VALUES ('carthur', 'Chester Arthur', 'DevOps Engineer', 'Prady, LLC', 'Department C');
INSERT INTO users VALUES ('gcleveland', 'Grover Cleveland', 'DevOps Engineer', 'Prady, LLC', 'Department A');
INSERT INTO users VALUES ('bharrison', 'Benjamin Harrison', 'DevOps Engineer', 'Prady, LLC', 'Department B');
INSERT INTO users VALUES ('wmckinley', 'William McKinley', 'Full Stack Developer', 'Prady, LLC', 'Department C');
INSERT INTO users VALUES ('troosevelt', 'Theodore Roosevelt', 'Full Stack Developer', 'Prady, LLC', 'Department A');
INSERT INTO users VALUES ('wtaft', 'William Taft', 'Full Stack Developer', 'Prady, LLC', 'Department B');
INSERT INTO users VALUES ('wwilson', 'Woodrow Wilson', 'Full Stack Developer', 'Prady, LLC', 'Department C');
INSERT INTO users VALUES ('wharding', 'Warren G. Harding', 'Full Stack Developer', 'Prady, LLC', 'Department A');
INSERT INTO users VALUES ('ccoolidge', 'Calvin Coolidge', 'FrontEnd Developer', 'Prady, LLC', 'Department B');
INSERT INTO users VALUES ('hhoover', 'Herbert Hoover', 'FrontEnd Developer', 'Prady, LLC', 'Department C');
INSERT INTO users VALUES ('fdroosevelt', 'Franklin D. Roosevelt', 'FrontEnd Developer', 'STSI', 'Department A');
INSERT INTO users VALUES ('htruman', 'Harry Truman', 'API Designer', 'STSI', 'Department B');
INSERT INTO users VALUES ('deisenhower', 'Dwight D. Eisenhower', 'Quality Assurance Expert', 'STSI', 'Department C');
INSERT INTO users VALUES ('jfkennedy', 'John F. Kennedy', 'Quality Assurance Expert', 'STSI', 'Department A');
INSERT INTO users VALUES ('lbjohnson', 'Lyndon B. Johnson', 'Quality Assurance Expert', 'STSI', 'Department B');
INSERT INTO users VALUES ('rnixon', 'Richard Nixon', 'Quality Assurance Expert', 'STSI', 'Department C');
INSERT INTO users VALUES ('gford', 'Gerald Ford', 'Logistics Support', 'STSI', 'Department A');
INSERT INTO users VALUES ('jcarter', 'Jimmy Carter', 'Logistics Support', 'STSI', 'Department B');
INSERT INTO users VALUES ('rreagan', 'Ronald Reagan', 'Product Owner', 'STSI', 'Department C');
INSERT INTO users VALUES ('gbush', 'George H. W. Bush', 'Agile Coach', 'STSI', 'Department A');
INSERT INTO users VALUES ('bclinton', 'Bill Clinton', 'Agile Coach', '540.co', 'Department B');
INSERT INTO users VALUES ('gwbush', 'George W. Bush', 'Agile Coach', '540.co', 'Department C');
INSERT INTO users VALUES ('bobama', 'Barack Obama', 'Agile Coach', '540.co', 'Department A');
