INSERT INTO users VALUES (1, 'gwashington', 'George Washington', 'CEO', 'STSI', 'Department A');
INSERT INTO users VALUES (2, 'jadams', 'John Adams', 'CTO', 'STSI', 'Department B');
INSERT INTO users VALUES (3, 'tjefferson', 'Thomas Jefferson', 'CFO', 'STSI', 'Department C');
INSERT INTO users VALUES (4, 'jmadison', 'James Madison', 'COO', 'STSI', 'Department A');
INSERT INTO users VALUES (5, 'jmonroe', 'James Monroe', 'Project Manager', 'STSI', 'Department B');
INSERT INTO users VALUES (6, 'jqadams', 'John Quincy Adams', 'Project Manager', 'STSI', 'Department C');
INSERT INTO users VALUES (7, 'ajackson', 'Andrew Jackson', 'Business Analyst', 'STSI', 'Department A');
INSERT INTO users VALUES (8, 'mvanburen', 'Martin Van Buren', 'Business Analyst', 'STSI', 'Department B');
INSERT INTO users VALUES (9, 'wharrison', 'William Harrison', 'Business Analyst', 'STSI', 'Department C');
INSERT INTO users VALUES (10, 'jtyler', 'John Tyler', 'Business Analyst', 'STSI', 'Department A');
INSERT INTO users VALUES (11, 'jpolk', 'James Polk', 'Business Analyst', '540.co', 'Department B');
INSERT INTO users VALUES (12, 'ztaylor', 'Zachery Taylor', 'Solutions Architect', '540.co', 'Department C');
INSERT INTO users VALUES (13, 'mfilmore', 'Millard Fillmore', 'Solutions Architect', '540.co', 'Department A');
INSERT INTO users VALUES (14, 'fpierce', 'Franklin Pierce', 'Solutions Architect', '540.co', 'Department B');
INSERT INTO users VALUES (15, 'jbuchanan', 'James Buchanan', 'ScrumMaster', '540.co', 'Department C');
INSERT INTO users VALUES (16, 'alincoln', 'Abraham Lincoln', 'ScrumMaster', '540.co', 'Department A');
INSERT INTO users VALUES (17, 'ajohnson', 'Andrew Johnson', 'UI/UX Expert', '540.co', 'Department B');
INSERT INTO users VALUES (18, 'ugrant', 'Ulysses S. Grant', 'UI/UX Expert', '540.co', 'Department C');
INSERT INTO users VALUES (19, 'rhayes', 'Rutherford B. Hayes', 'UI/UX Expert', '540.co', 'Department A');
INSERT INTO users VALUES (20, 'jgarfield', 'James Garfield', 'UI/UX Expert', '540.co', 'Department B');
INSERT INTO users VALUES (21, 'carthur', 'Chester Arthur', 'DevOps Engineer', 'Prady, LLC', 'Department C');
INSERT INTO users VALUES (22, 'gcleveland', 'Grover Cleveland', 'DevOps Engineer', 'Prady, LLC', 'Department A');
INSERT INTO users VALUES (23, 'bharrison', 'Benjamin Harrison', 'DevOps Engineer', 'Prady, LLC', 'Department B');
INSERT INTO users VALUES (24, 'wmckinley', 'William McKinley', 'Full Stack Developer', 'Prady, LLC', 'Department C');
INSERT INTO users VALUES (25, 'troosevelt', 'Theodore Roosevelt', 'Full Stack Developer', 'Prady, LLC', 'Department A');
INSERT INTO users VALUES (26, 'wtaft', 'William Taft', 'Full Stack Developer', 'Prady, LLC', 'Department B');
INSERT INTO users VALUES (27, 'wwilson', 'Woodrow Wilson', 'Full Stack Developer', 'Prady, LLC', 'Department C');
INSERT INTO users VALUES (28, 'wharding', 'Warren G. Harding', 'Full Stack Developer', 'Prady, LLC', 'Department A');
INSERT INTO users VALUES (29, 'ccoolidge', 'Calvin Coolidge', 'FrontEnd Developer', 'Prady, LLC', 'Department B');
INSERT INTO users VALUES (30, 'hhoover', 'Herbert Hoover', 'FrontEnd Developer', 'Prady, LLC', 'Department C');
INSERT INTO users VALUES (31, 'fdroosevelt', 'Franklin D. Roosevelt', 'FrontEnd Developer', 'STSI', 'Department A');
INSERT INTO users VALUES (32, 'htruman', 'Harry Truman', 'API Designer', 'STSI', 'Department B');
INSERT INTO users VALUES (33, 'deisenhower', 'Dwight D. Eisenhower', 'Quality Assurance Expert', 'STSI', 'Department C');
INSERT INTO users VALUES (34, 'jfkennedy', 'John F. Kennedy', 'Quality Assurance Expert', 'STSI', 'Department A');
INSERT INTO users VALUES (35, 'lbjohnson', 'Lyndon B. Johnson', 'Quality Assurance Expert', 'STSI', 'Department B');
INSERT INTO users VALUES (36, 'rnixon', 'Richard Nixon', 'Quality Assurance Expert', 'STSI', 'Department C');
INSERT INTO users VALUES (37, 'gford', 'Gerald Ford', 'Logistics Support', 'STSI', 'Department A');
INSERT INTO users VALUES (38, 'jcarter', 'Jimmy Carter', 'Logistics Support', 'STSI', 'Department B');
INSERT INTO users VALUES (39, 'rreagan', 'Ronald Reagan', 'Product Owner', 'STSI', 'Department C');
INSERT INTO users VALUES (40, 'gbush', 'George H. W. Bush', 'Agile Coach', 'STSI', 'Department A');
INSERT INTO users VALUES (41, 'bclinton', 'Bill Clinton', 'Agile Coach', '540.co', 'Department B');
INSERT INTO users VALUES (42, 'gwbush', 'George W. Bush', 'Agile Coach', '540.co', 'Department C');
INSERT INTO users VALUES (43, 'bobama', 'Barack Obama', 'Agile Coach', '540.co', 'Department A');
